package tests;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;
import java.util.*;

public class DeleteStudentTest {
 private WebDriver driver;
 private Map<String, Object> vars;
 JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<>();
}
@After
public void tearDown() {
 driver.quit();
}
    @Test
public void delete() {
 driver.get("http://localhost:4200/");
 driver.manage().window().setSize(new Dimension(968, 814));   
 driver.findElement(By.xpath("//*[@id=\"DataTables_Table_0\"]/tbody/tr[4]/td[4]/button[1]")).click();
 WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
 wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"DataTables_Table_0\"]/tbody/tr")));
 vars.put("x", driver.findElements(By.xpath("//*[@id=\"DataTables_Table_0\"]/tbody/tr")).size());
 System.out.println("Broj redova nakon brisanja: " + vars.get("x").toString());
 assertEquals("4", vars.get("x").toString());
 driver.close();
 }
}
