package tests;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class UpdateStudentTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void update() {
 driver.get("http://localhost:4200/");
 driver.manage().window().setSize(new Dimension(968, 814));
 driver.findElement(By.cssSelector(".odd:nth-child(1) .btn-info")).click();
 driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
 driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("Jovana Kosovac");
 driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).click();
 driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).sendKeys("jovanakosovac@gmail.com");
 driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control")).click();
 {
   WebElement dropdown = driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control"));
   dropdown.findElement(By.xpath("//option[. = 'BCA']")).click();
 }
 driver.findElement(By.cssSelector(".btn-success")).click();
 driver.findElement(By.cssSelector(".btn-danger")).click();
 driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(1)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(1)")).getText(), "markomarkovic@gmail.com");
 driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(3)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(3)")).getText(), "abca");
 vars.put("x", driver.findElements(By.xpath("//*[@id=\"DataTables_Table_0\"]/tbody/tr")).size());
 System.out.println(vars.get("x").toString());
 assertEquals(vars.get("x").toString(), "5");
}
}