package tests;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class ViewStudentsTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void view() {
 driver.get("http://localhost:4200/");
 driver.manage().window().setSize(new Dimension(968, 814));
 driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(1)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(1)")).getText(), "markomarkovic@gmail.com");
 driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(3)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(3)")).getText(), "abca");
 driver.findElement(By.cssSelector(".even:nth-child(2) > td:nth-child(1)")).click();
 assertEquals(driver.findElement(By.cssSelector(".even:nth-child(2) > td:nth-child(1)")).getText(), "milanamilic@gmail.com");
 driver.findElement(By.cssSelector(".even:nth-child(2) > td:nth-child(3)")).click();
 assertEquals(driver.findElement(By.cssSelector(".even:nth-child(2) > td:nth-child(3)")).getText(), "ab-tech");
 driver.findElement(By.cssSelector(".odd:nth-child(3) > td:nth-child(1)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(3) > td:nth-child(1)")).getText(), "petarpetrovic@gmail.com");
 driver.findElement(By.cssSelector(".odd:nth-child(3) > td:nth-child(3)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(3) > td:nth-child(3)")).getText(), "am-tech");
 driver.findElement(By.cssSelector(".even:nth-child(4) > td:nth-child(1)")).click();
 assertEquals(driver.findElement(By.cssSelector(".even:nth-child(4) > td:nth-child(1)")).getText(), "sarasaric@gmail.com");
 driver.findElement(By.cssSelector(".even:nth-child(4) > td:nth-child(3)")).click();
 assertEquals(driver.findElement(By.cssSelector(".even:nth-child(4) > td:nth-child(3)")).getText(), "amca");
 driver.findElement(By.cssSelector(".odd:nth-child(5) > td:nth-child(1)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(5) > td:nth-child(1)")).getText(), "tamarakosovac@gmail.com");
 driver.findElement(By.cssSelector(".odd:nth-child(5) > td:nth-child(3)")).click();
 assertEquals(driver.findElement(By.cssSelector(".odd:nth-child(5) > td:nth-child(3)")).getText(), "ab-tech");
 vars.put("x", driver.findElements(By.xpath("//*[@id=\"DataTables_Table_0\"]/tbody/tr")).size());
 System.out.println(vars.get("x").toString());
 assertEquals(vars.get("x").toString(), "5");
}
}
